# Generated by Django 5.1.4 on 2024-12-08 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
