# Generated by Django 5.1.4 on 2024-12-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0004_rename_messages_ids_board_messages_uuids_board_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='messages_uuids',
            field=models.TextField(blank=True),
        ),
    ]
