# Generated by Django 5.1.4 on 2024-12-09 02:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0006_alter_board_uuid_alter_message_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='uuid',
            field=models.CharField(default=uuid.uuid1, editable=False, max_length=120, unique=True),
        ),
    ]
