# Generated by Django 5.1.4 on 2024-12-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0008_alter_message_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
