# Generated by Django 5.1.4 on 2024-12-22 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0009_board_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Forum.board'),
        ),
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
