# Generated by Django 5.1.4 on 2024-12-22 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0010_message_board_alter_board_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='messages_uuids',
        ),
        migrations.AlterField(
            model_name='message',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.board'),
        ),
    ]
